IPAA_APP/IPAA_APP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Polls/', include('Polls.urls')),
    path('Portfolio/', include('Portfolio.urls')),
    path('Simulation/', include('Simulation.urls')),
    path('', RedirectView.as_view(url='Polls/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

IPAA_APP/Polls/urls.py
from django.urls import path
from . import views

app_name = 'IPAA'
urlpatterns = [
    path('', views.index, name='index'),
    path('questions', views.questions, name='questions'),
    path('polls', views.polls, name='polls'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('<int:pk>/simulation', views.simulation, name='simulation'),
    path('end', views.end, name='end'),
    path('error', views.error, name='error'),
    path('config', views.config, name='config'),
    path('configCluster', views.configCluster, name='configCluster'),
    path('motivo', views.motivo, name='motivo'),

]

IPAA_APP/Portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [

]

IPAA_APP/Simulation/urls.py
from django.urls import path
from . import views

urlpatterns = [

]

IPAA_APP/Polls/models.py
from typing import Reversible
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.

#
# Motivos de alteração na carteira


class Motivo(models.Model):
    nome = models.CharField(
        max_length=100, help_text='Informe o nome do motivo')

    aparece = models.BooleanField()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Motivo'
        verbose_name_plural = '4. Motivos'

#
# Grau de instrução


class Grau_Instrucao(models.Model):
    nome = models.CharField(
        max_length=100, help_text='Informe o grau de instrução')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Grau de Instrução'
        verbose_name_plural = '2. Graus de Instrução'

#
# Profissão


class Profissao(models.Model):
    nome = models.CharField(
        max_length=100, help_text='Informe o nome da profissão')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Profissão'
        verbose_name_plural = '3. Profissões'

#
# Ações


class Acao(models.Model):
    codigo = models.CharField(
        max_length=10, help_text='Informe o código da ação')

    nome = models.CharField(
        max_length=100, help_text='Informe o nome da ação')

    split = models.BooleanField(
        null=True, default=False
    )

    def __str__(self):
        return self.codigo

    class Meta:
        verbose_name = 'Ação'
        verbose_name_plural = '5. Ações'

#
# Perfis


class Perfil(models.Model):
    nome = models.CharField(
        max_length=100, help_text='Informe o nome do perfil')

    peso_inicial = models.IntegerField()

    peso_final = models.IntegerField()

    tipo = models.CharField(
        max_length=50, help_text='Informe o tipo de perfil')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = '1. Perfis'

#
# Perguntas


class Pergunta(models.Model):
    pergunta = models.CharField(
        max_length=500, help_text='Informe a pergunta')

    status = models.BooleanField()

    sequencia = models.IntegerField()

    def __str__(self):
        return self.pergunta

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return Reversible('poll-detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'Pergunta'
        verbose_name_plural = '6. Perguntas'

#
# Respostas


class Resposta(models.Model):

    pergunta = models.ForeignKey(
        Pergunta, on_delete=models.CASCADE, null=False)

    resposta = models.CharField(
        max_length=200, help_text='Informe a resposta')

    sequencia = models.IntegerField()

    pontuacao = models.DecimalField(
        max_digits=6, decimal_places=4)

    def __str__(self):
        return self.resposta

    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = '7. Respostas'


#
# Usuario


class Usuario(models.Model):

    idade = models.IntegerField()

    sexo = (
        ('m', 'Masculino'),
        ('f', 'Feminino'),
    )

    genero = models.CharField(
        max_length=1,
        choices=sexo,
        blank=True,
        help_text='Gênero',
    )

    grau_instrucao = models.ForeignKey(
        Grau_Instrucao, on_delete=models.SET_NULL, null=True)

    profissao = models.ForeignKey(
        Profissao, on_delete=models.SET_NULL, null=True)

    data_cadastro = models.DateTimeField(
        null=False, blank=False, auto_now_add=True)

    perfil = models.ForeignKey(
        Perfil, on_delete=models.SET_NULL, null=True)

    USERNAME_FIELD = 'id'

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = '8. Usuários'

#
# Respostas_usuario


class Respostas_usuario(models.Model):

    data_inicial = models.DateTimeField(
        null=False, blank=False)

    data_final = models.DateTimeField(
        null=False, blank=False, auto_now_add=True)

    resposta = models.ForeignKey(
        Resposta, on_delete=models.RESTRICT, null=False)

    usuario = models.ForeignKey(
        Usuario, on_delete=models.RESTRICT, null=False)

    def __str__(self):
        return self.resposta.resposta

    class Meta:
        verbose_name = 'Resposta do Usuário'
        verbose_name_plural = '99. Respostas dos Usuários'


# Simulação


class Simulacao_cenarios(models.Model):
    nome = models.CharField(
        max_length=100, help_text='Informe o nome da simulação')

    descricao = models.CharField(
        max_length=300, help_text='Informe a descrição da simulação', null=True)

    data_ini = models.DateField(
        null=False, blank=False)

    data_fim = models.DateField(
        null=False, blank=False)

    indice_previsao = models.IntegerField(
        blank=True, null=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Simulação'
        verbose_name_plural = '9. Simulações'

IPAA_APP/Polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from Polls.models import Simulacao_cenarios
from Polls.portfolio import calculaPortfolio
from Polls.security import checkAccess
from Polls.simulation import calculaSimulacoes
from Portfolio.stockClustering import CategorizacaoAcoes
from Portfolio.stockPrediction import PrevisaoAcoes
from Portfolio.stockProfile import PerfilInvestimento
from .forms import MotivoForm, RegisterUserForm, SurveyForm, PortfolioForm, SimulatiomForm


# PAGINA INICIAL
def index(request):

    if request.method == 'POST':

        return redirect('IPAA:questions')

    context = {
        # 'url': url,
    }

    return render(request, 'intro.html', context)

# PAGINA DAS PERGUNTAS INICIAIS


def questions(request):
    form = RegisterUserForm()

    if request.method == 'POST':
        try:
            form = RegisterUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                request.session['usuario'] = user.id
                request.session['url'] = 'IPAA:polls'
                request.session['simula'] = None
                request.session['trava'] = False

                return redirect('IPAA:polls')
            else:
                for field in form:
                    print("Field Error:", field.name,  field.errors)
        except Exception as e:
            print(e)
            raise

    context = {
        'form': form,
    }

    return render(request, 'index.html', context)

# PAGINA DE AGRUPAMENTO DE AÇÕES


def configCluster(request):

    simulacoes = Simulacao_cenarios.objects.all()

    info = []
    for simula in simulacoes:

        # Categoriza conforme dados reais
        if (simula.id == calculaSimulacoes.getSimulacaoInicial().id):
            CategorizacaoAcoes.clusterizaoPrimeiroCenario(simula=simula)
        else:
            # Categoriza conforme previsao
            CategorizacaoAcoes.clusterizacaoCenariosSimulacao(simula=simula)
            print('')

        info.extend(CategorizacaoAcoes.logCl)

    context = {
        'infos': info,
    }

    return render(request, 'configCluster.html', context)

# PAGINA DE PREVISAO DOS VALORES DAS AÇÕES


def config(request):

    simulacoes = calculaSimulacoes.getAllSimulacao()
    pos = 0
    PrevisaoAcoes.info = []

    for simula in simulacoes:
        PrevisaoAcoes.calculaPrevisaoSimulacao(simula, pos)
        pos += 1

    context = {
        'infos': PrevisaoAcoes.info,
    }

    return render(request, 'config.html', context)

# PAGINA DE PERGUNTAS


def polls(request):

    userid = request.session['usuario']

    if (checkAccess.canAccessPolls(userid) == False):
        return redirect('IPAA:error')

    form = SurveyForm()

    if request.method == 'POST':
        try:
            form = SurveyForm(request.POST)
            if form.is_valid():
                form = form.save(userid)
                request.session['url'] = 'IPAA:portfolio'
                return redirect('IPAA:portfolio')
            else:
                for field in form:
                    print("Field Error:", field.name,  field.errors)
        except Exception as e:
            print(e)
            raise

    context = {
        "form": form,
    }
    return render(request, 'polls.html', context)

# PAGINA DA GERAÇÃO DA CARTEIRA


def portfolio(request):
    userid = request.session['usuario']

    tipo = userid % 2

    if (request.session['trava'] and checkAccess.canAccessSimulation(userid, None) == False):
        return redirect('IPAA:error')

    perf = calculaPortfolio.verificaPerfil(userid)

    acoesRec = None

    if (tipo == 0):  # busca as recomendações de IA
        acoesRec = PerfilInvestimento.getAcoesByPerfil(
            perf, calculaSimulacoes.getSimulacaoInicial())

    # cria a carteira inicial sem ações
    cart = calculaPortfolio.criaCarteiraSemAcoes(
        userid, tipo)

    form = PortfolioForm()

    # Cria os caampos na tela
    PortfolioForm.getAcoesPortfolio(form, acoesRec)

    simulacao = calculaSimulacoes.getSimulacaoInicial()

    listAll = calculaSimulacoes.getInfAcoesPortofolio(
        form, simulacao)

    if request.method == 'POST':
        post = request.POST
        form = PortfolioForm(post)

        form.cleanCheck(calculaSimulacoes.getAcoesSimulacoes(
            simulacao), post)

        if form.is_valid():
            selected = form.save(
                calculaSimulacoes.getAcoesSimulacoes(simulacao), post)

            idSimula = calculaSimulacoes.getPrimeiraSimulacao().id

            request.session['url'] = 'IPAA:simulation'
            request.session['simula'] = idSimula

            calculaPortfolio.salvaPortfolio(cart, selected, acoesRec, None)
            calculaPortfolio.criaAcoesCarteira(cart, selected)

            request.session['cenario_atual'] = 1

            if (tipo == 1):
                return HttpResponseRedirect(reverse('IPAA:simulation', args=(idSimula,)))

            simulaIni = calculaSimulacoes.getSimulacaoInicial()

            # verifica se houve algo que o usuaraio nao seguiu
            hist = calculaPortfolio.getNaoSeguiuRecomendacao(
                simula=simulaIni, carteira=cart)

            if (hist == None):
                return HttpResponseRedirect(reverse('IPAA:simulation', args=(idSimula,)))
            else:
                return redirect('IPAA:motivo')

        else:
            for field in form:
                print("Field Error:", field.name,  field.errors)

    context = {
        "perf": perf,
        "form": form,
        "lista": listAll,
        "cart": cart,
        "simulacao": simulacao
    }
    return render(request, 'portfolio.html', context)

# PAGINA DAS SIMULAÇÕES


def simulation(request, pk):

    userid = request.session['usuario']
    request.session['trava'] = True

    simulacao = get_object_or_404(Simulacao_cenarios, id=pk)

    if (checkAccess.canAccessSimulation(userid, simulacao) == False):
        return redirect('IPAA:error')

    form = SimulatiomForm()

    # Busca a carteira do usuario
    cartUser = SimulatiomForm.getCarteira(userid)

    qtde = calculaSimulacoes.getQtdeSimulacoes()

    ultimoCenario = not request.session['cenario_atual'] < qtde

    acoesRec = None

    if (cartUser.tipo_grupo == 0):  # Busca as recomendações de IA
        acoesRec = PerfilInvestimento.getAcoesByPerfil(
            cartUser.usuario.perfil, simulacao)

    # Criar os campos na tela
    SimulatiomForm.getAcoesSimulacao(form, simulacao, ultimoCenario, acoesRec)

    listAll = calculaSimulacoes.getInfAcoesSimulacaoes(
        form, simulacao, cartUser)

    # busca o percentual
    percent = calculaSimulacoes.getPercentualCarteira(cartUser, simulacao)

    percentA = calculaSimulacoes.getPercentualAcumuladoCarteira(
        carteira=cartUser) + percent

    if request.method == 'POST':
        post = request.POST
        form = SimulatiomForm(post)

        form.cleanCheck(calculaSimulacoes.getAcoesSimulacoes(
            simulacao), post, ultimoCenario)

        if form.is_valid():

            # salva o percentual que a carteira subiu naquela simulação
            calculaSimulacoes.salvaCarteiraSimulacao(
                cartUser, percent, request.session['cenario_atual'])

            selected = form.save(
                calculaSimulacoes.getAcoesSimulacoes(simulacao), post)

            calculaPortfolio.salvaPortfolio(
                cartUser, selected, acoesRec, simulacao)

            if (not ultimoCenario):

                request.session['cenario_atual'] = request.session['cenario_atual'] + 1

                idSimula = calculaSimulacoes.getSimulacaoPos(
                    request.session['cenario_atual']).id

                request.session['url'] = 'IPAA:simulation'
                request.session['simula'] = idSimula

                if (cartUser.tipo_grupo == 1):
                    return HttpResponseRedirect(reverse('IPAA:simulation', args=(idSimula,)))

                 # verifica se houve algo que o usuaraio nao seguiu
                hist = calculaPortfolio.getNaoSeguiuRecomendacao(
                    simula=simulacao, carteira=cartUser)

                if (hist == None):
                    return HttpResponseRedirect(reverse('IPAA:simulation', args=(idSimula,)))
                else:
                    return redirect('IPAA:motivo')

            else:
                return redirect('IPAA:end')

        else:
            print('not valid')
            print(form.errors)
            for field in form:
                print("Field Error:", field.name,  field.errors)

    context = {
        "form": form,
        "simulacao": simulacao,
        "qtde": qtde,
        "atual": request.session['cenario_atual'],
        "lista": listAll,
        "percent": percent,
        "percentA": percentA
    }
    return render(request, 'simulation.html', context)

# PAGINA QUE O USUARIO INFORMA O MOTIVO


def motivo(request):

    url = request.session['url']
    userid = request.session['usuario']
    nextSimula = request.session['simula']
    atual = request.session['cenario_atual']

    # Busca a carteira do usuario
    cartUser = SimulatiomForm.getCarteira(userid)
    simulaPre = calculaSimulacoes.getSimulacaoPre(atual=atual)

    form = MotivoForm(simulaPre, cartUser)

    if request.method == 'POST':
        form = MotivoForm(simulaPre, cartUser, request.POST)
        if form.is_valid():
            form = form.save()

            return HttpResponseRedirect(reverse(url, args=(nextSimula,)))
    context = {
        "form": form
    }

    return render(request, 'motivo.html', context)

# PAGINA FINAL


def end(request):

    userid = request.session['usuario']

    # Busca a carteira do usuario
    cartUser = SimulatiomForm.getCarteira(userid)

    percentA = calculaSimulacoes.getPercentualAcumuladoCarteira(
        carteira=cartUser)

    if request.method == 'POST':

IPAA_APP/Portfolio/views.py
from django.shortcuts import render

# Create your views here.

IPAA_APP/Simulation/views.py
from django.shortcuts import render

# Create your views here.

IPAA_APP/Polls/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>IPAA</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="">All books</a></li>
          <li><a href="">All authors</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

IPAA_APP/Polls/templates/config.html
{% extends 'layouts/page.html' %}


{% block content %}


<div class="page register-page">
    <div class="header">
        <h1 class="title">Página para configurações iniciais</h1>
    </div>

    <h3 class="subtitle">Página utilizada para parametrização inicial da Inteligência Artificial</h3>
</div>

<div class="acao-item">
    
    <table >
        <tr>
        <td class="td-title-name">Log</td>
        </tr>
            {% for info in infos %}
            <tr>
            <td>
                {{ info }}
            </td>
            </tr>
            {% endfor %}
    
</div>

{% endblock %}

IPAA_APP/Polls/templates/configCluster.html
{% extends 'layouts/page.html' %}


{% block content %}


<div class="page register-page">
    <div class="header">
        <h1 class="title">Configurações de Clusterização</h1>
    </div>

    <h3 class="subtitle">Página utilizada para parametrização inicial da Inteligência Artificial - Clusters</h3>
</div>

<div class="acao-item">
    
    <table >
        <tr>
        <td class="td-title-name">Log</td>
        </tr>
            {% for info in infos %}
            <tr>
            <td>
                {{ info }}
            </td>
            </tr>
            {% endfor %}
    
</div>

{% endblock %}

IPAA_APP/Polls/templates/detail.html
<h1>{{ Pergunta.pergunta }}</h1>
<ul>
{% for Resposta in Pergunta.resposta_set.all %}
    <li>{{ Resposta.resposta }}</li>
{% endfor %}
</ul>

IPAA_APP/Polls/templates/end.html
{% extends 'layouts/page.html' %}


{% block content %}


<div class="page register-page">
    <div class="header">
        <h1 class="title">Obrigado!</h1>
    </div>

    <h3 class="subtitle">O Desempenho Acumulado de sua Carteira foi: <u>{{ percentA |floatformat:2 }}%</u>
    </br></br>Muito obrigado por participar dessa pesquisa.</h3>
</div>


{% endblock %}

IPAA_APP/Polls/templates/error.html
{% extends 'layouts/page.html' %}


{% block content %}


<div class="page register-page">
    <div class="header">
        <h1 class="title">OPS</h1>
    </div>

    <h3 class="subtitle">Você não pode acessar essa página.</h3>
    
    <form method="POST" action="" class="register-form"> {% csrf_token %}
        <input type="submit" value="Clique aqui para voltar" class="submit-button-error"/>
    </form>


</div>


{% endblock %}

IPAA_APP/Polls/templates/index.html
{% extends 'layouts/page.html' %}

{% block content %}
<div class="page register-page">
    <div class="header">
    <h1 class="title">Dados Iniciais</h1>
    </div>
    <h3 class="subtitle">Por favor, informe seus dados abaixo:</h3>
    
    
    <form method="POST" action="" class="register-form"> {% csrf_token %}
        <div class="fieldWrapper">
            <label for="{{form.idade.id_for_label}}">Informe sua idade:</label>
                {{form.idade}}
            <span class="error">{{form.idade.errors}}</span>
        </div>

        <div class="fieldWrapper">
            <label for="{{form.genero.id_for_label}}">Sexo:</label>
                {{form.genero}}
            <span class="error">{{form.genero.errors}}</span>
        </div>

        <div class="fieldWrapper">
            <label for="{{form.grau_instrucao.id_for_label}}">Grau de Instrução:</label>
                {{form.grau_instrucao}}
            <span class="error">{{form.grau_instrucao.errors}}</span>
        </div>

        <div class="fieldWrapper">
            <label for="{{form.profissao.id_for_label}}">Profissão:</label>
                {{form.profissao}}
            <span class="error">{{form.profissao.errors}}</span>
        </div>

        {% if form.non_field_errors %}
            <div class="non_form_errors">
                <span class="error">
                    {{form.non_field_errors.as_ul}}
                </span>
            </div>
        {% endif %} 
        <input type="submit" value="Próximo" class="submit-button"/>
    </form>
</div> 

{% endblock %}

IPAA_APP/Polls/templates/intro.html
{% extends 'layouts/page.html' %}


{% block content %}


<div class="page register-page">
    <div class="header">
        <h1 class="title">Introdução</h1>
    </div>

    <h4 class="subtitle"><b>Prezado respondente, este estudo é uma pesquisa desenvolvida para analisar o comportamento do investidor. 
        </br>Possui como objetivo analisar se a </b>“INTELIGÊNCIA ARTIFICIAL” <b>auxilia de alguma forma neste comportamento, evitando os vieses comportamentais.</b>
    </br></br>COMO UTILIZAR O SIMULADOR:
    </h4>
    <div class="intro">
        <p>1.	Irá preencher os dados de perfil;</p>
        <p>2.	Irá responder o questionário o qual determinara o seu perfil de investidor;</p>
        <p>3.	Será destinado aleatoriamente para um dos dois grupos da pesquisa: com auxílio da IA e sem auxílio da IA;</p>
        <p>4.	Será direcionado ao simulador, o qual terá que marcar as ações a qual deseja manter em sua carteira de investimentos, 
            período após período; (desmarque para <b>“vender”</b> uma ação, removendo ela de sua carteira, ou pode marcar uma ação para <b>“comprar”</b>, incluindo ela em sua carteira.)</p>
        <p>5.	Ao final das simulações receberá seu Desempenho acumulado de todos os períodos.</p>
    </div>

    <form method="POST" action="" class="register-form"> {% csrf_token %}
        <input type="submit" value="Clique aqui para Iniciar" class="submit-button-error"/>
    </form>
</div>


{% endblock %}

IPAA_APP/Polls/templates/motivo.html
{% extends 'layouts/page.html' %}


{% block content %}


<div class="page register-page">
    <div class="header">
        <h1 class="title">Motivo Alteração</h1>
    </div>

    <h3 class="subtitle">As seguintes ações abaixo não fazem parte da recomendação da Inteligência Artificial ou você as removeu da recomendação de sua carteira. 
    </br>Por favor, informe o motivo para cada uma das operações que fez.
    </h3>

    <form method="POST" action="" class="register-form"> {% csrf_token %}
        <div class="question-list-item">
            {{ form.as_p }}
        </div>
        <input type="submit" value="Próximo" class="submit-button"/>
    </form>
</div>


{% endblock %}

IPAA_APP/Polls/templates/navbar.html
<nav class="navbar">
    <div class="main-menu">
        <ul>
            <li></li>
        </ul>
    </div>
    <div class="user-menu">

    </div>
</nav>

IPAA_APP/Polls/templates/perguntas_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Perguntas</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ pergunta.get_absolute_url }}">{{ pergunta.pergunta }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Não existem perguntas cadastradas.</p>
  {% endif %}
{% endblock %}

IPAA_APP/Polls/templates/polls.html
{% extends 'layouts/page.html' %}

{% block content %}
<div class="page register-page">
    <div class="header">
        <h1 class="title">Perfil de Investidor</h1>
    </div>
    <h3 class="subtitle">Responda as perguntas abaixo para identificar seu perfil de investidor</h3>
    <form method="POST" action="" class="register-form"> {% csrf_token %}
        <div class="question-list-item">
            {{ form.as_p }}
        </div>
        <input type="submit" value="Próximo" class="submit-button"/>
    </form>
</div>
{% endblock %}

IPAA_APP/Polls/templates/portfolio.html
{% extends 'layouts/page.html' %}

{% block content %}
<div class="page register-page">
    <div class="header">
        <h1 class="title">Identificação do seu Perfil</h1>
    </div>
    <h3 class="subtitle">Com base nas respostas anteriores, o perfil indicado para você é:</h3>

    <div class="profile">
            <u>{{ perf }}</u>
    </div>
    
    {% if cart.tipo_grupo == 0 %}
        <h3 class="grupo-cart">
            Você foi selecionado para o grupo de <b>recomendações da inteligência artificial.</b></br>
            Portanto, as Ações recomendadas para você são: 
        </h3>
    {% else %}
        <h3 class="grupo-cart">
            Você está no grupo de criação <b>manual</b> de carteira e <b><u>não</u></b> receberá recomendações da inteligência artificial.</br>
            A sua carteira será composta por todas ações que estiverem flegadas dentro de cada simulação.</br>
            Por favor, selecione abaixo quais dessas ações você gostaria de ter na sua carteira: 
        </h3>
    {% endif %} 

    <form method="POST" action="" class="register-form"> {% csrf_token %}
        
        <div class="acao-item">
            <table >
                <tr>
                    <td></td>
                    <td class="td-title-name-port">Ação</td>
                    <td class="td-title">Preço Atual</td>
                    <td class="td-title">Rentabilidade (%)</td>
                </tr>
            {% for fieldInfo in lista %}
                <tr>
                <td>{{ fieldInfo.field }} </td> 
                <td> {{ fieldInfo.field.label}}  </td> 
                <td class="td-number"> R$ {{ fieldInfo.valorAtual }}</td>
                    {% if fieldInfo.percent < 0%}
                        <td class="NegativeTransaction">{{ fieldInfo.percent|floatformat:2 }} %</td>
                    {% else %}
                        <td class="PositiveTransaction">{{ fieldInfo.percent|floatformat:2 }} %</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </table>
            
        </div>
        
        <div style="text-align: center;">
            <b>NOTA: </b>Rentabilidade com base nos valores do Período: <b>{{ simulacao.data_ini|date:"d/m/Y"}} até {{ simulacao.data_fim|date:"d/m/Y" }}</b>
        </div>

        <div class="question-list-error">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                       {{ error|escape }}
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
        
        <input type="submit" value="Próximo" class="submit-button"/>
    </form>
</div>


{% endblock %}